<?php 


echo '<ul class="nav" id="side-menu">';
					
echo '					<li>';
echo '						<a href="#" class="active"><i class="fa fa-cubes fa-fw"></i> Dispositivos<span class="fa arrow"></span></a>';
echo '						<ul class="nav nav-second-level">';
echo '							<li>';
echo '								<a href="devices.php">Dashboard</a>';
echo '							</li>';
echo '							<li>';
echo '								<a href="devices_adicionar.php">Adicionar Dispositivo</a>';
echo '							</li>';
echo '							<li>';
echo '								<a href="devices_editar.php">Editar Dispositivo</a>';
echo '							</li>';
echo '							<li>';
echo '								<a href="devices_excluir.php">Excluir Dispositivo</a>';
echo '							</li>';
echo '							<li>';
echo '								<a href="devices_logs.php">Logs Dispositivo</a>';
echo '							</li>';
echo '						</ul>';
echo '						<!-- /.nav-second-level -->';
echo '					</li>';
echo '					<li>';
echo '						<a href="#" class="active"><i class="fa fa-cube fa-fw"></i> Perfil<span class="fa arrow"></span></a>';
echo '						<ul class="nav nav-second-level">';
echo '							<li>';
echo '								<a href="profile.php">Adicionar Perfil</a>';
echo '							</li>';
echo '							<li>';
echo '								<a href="profile_vinc.php">Vinculações Perfil</a>';
echo '							</li>';
echo '						</ul>';
echo '					</li>';
echo '					<li>';
echo '						<a href="parameters.php" class="active"><i class="fa fa-list fa-fw"></i> Parâmetros</a>';
echo '					</li>';
echo '					<li>';
echo '						<a href="scripts.php" class="active"><i class="fa fa-tasks fa-fw"></i> Scripts</a>';
echo '					</li>';
echo '					<li>';
echo '						<a href="tableARP.php" class="active"><i class="fa fa-exchange fa-fw"></i> Tabela ARP</a>';
echo '					</li>';
echo '					<li>';
echo '						<a href="tableROUTE.php" class="active"><i class="fa fa-location-arrow fa-fw"></i> Tabela Roteamento</a>';
echo '					</li>';
echo '					<li>';
echo '						<a href="#" class="active"><i class="fa fa-sheqel fa-fw"></i> Serviços<span class="fa arrow"></span></a>';
echo '						<ul class="nav nav-second-level">';
echo '							<li>';
echo '								<a href="bindings.php">Adicionar Serviços</a>';
echo '							</li>';
echo '							<li>';
echo '								<a href="bindings_vinc.php">Vinculações de Serviços</a>';
echo '							</li>';
echo '						</ul>';
echo '					</li>';
echo '					<li>';
echo '						<a href="#" class="active"><i class="fa fa-play fa-fw"></i> Executar<span class="fa arrow"></span></a>';
echo '						<ul class="nav nav-second-level">';
echo '							<li>';
echo '								<a href="run.php">Liberar Serviços</a>';
echo '							</li>';
echo '							<li>';
echo '								<a href="run_finalizados.php">Finalizados</a>';
echo '							</li>';
echo '							<li>';
echo '								<a href="run_monitora.php">Monitoramento</a>';
echo '							</li>';
echo '						</ul>';
echo '					</li>';
echo '					<li>';
echo '						<a href="#" class="active"><i class="fa fa-bar-chart fa-fw"></i> Resultados<span class="fa arrow"></span></a>';
echo '						<ul class="nav nav-second-level">';
echo '							<li>';
echo '								<a href="results_responsetime.php">Response Time</a>';
echo '							</li>';
echo '							<li>';
echo '								<a href="results_dnshealth.php">DNS Health</a>';
echo '							</li>';
echo '							<li>';
echo '								<a href="results_servicosiperf.php">Serviços de IPERF</a>';
echo '							</li>';
echo '							<li>';
echo '								<a href="results_dhcphealth.php">DHCP Health</a>';
echo '							</li>';
echo '						</ul>';
echo '					</li>';
echo '				</ul>';


?>